### ISSUE TITLE
webrick is not part of the default gems since Ruby 3.0.0

### ISSUE THREAD

**Issue by chenrui333** [garybernhardt/serveit#13]
seeing some runtime failure when running with ruby 3.3

```
  webrick is not part of the default gems since Ruby 3.0.0. Install webrick from RubyGems.
  <internal:/home/linuxbrew/.linuxbrew/Cellar/ruby/3.3.4/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- webrick (LoadError)
```

**Comment by garybernhardt** [comment]
Did you install it? If so, did it work?

**Comment by chenrui333** [comment]
yeah, I have included webrick gem and seems passing the brew test

relates to https://github.com/Homebrew/homebrew-core/pull/179624

**Comment by garybernhardt** [comment]
Excellent, thank you for figuring it out and PRing that homebrew update. I just updated the README to mention that serveit now requires a dependency when running on Ruby 3.x.
