### ISSUE TITLE
questions: What versions of ruby are supported?

### ISSUE THREAD

**Issue by jasonkarns** [garybernhardt/serveit#2]

**Comment by garybernhardt** [comment]
I didn't really think about it, but it works on 1.9.3 so I'm gonna say 1.9.3+?

**Comment by garybernhardt** [comment]
I added a note to the README

**Comment by jasonkarns** [comment]
Cool. I was only curious so that I knew which version to set as a requirement in the brew formula.
https://github.com/Homebrew/homebrew-head-only/pull/96
