### ISSUE TITLE
Rack interface?

### ISSUE THREAD

**Issue by krasnoukhov** [garybernhardt/serveit#4]
Hey, serveit looks really nice and simple solution. I'm wondering would you be interested in having Rack interface? For example, It would be nice to use it with [pow](http://pow.cx/). Please let me now what you think!

**Comment by garybernhardt** [comment]
It used to use Rack internally, but I removed it because I don't want it to have any dependencies.

Why do you want to use it with another server?

**Comment by krasnoukhov** [comment]
Well, it's just for simpler use. I know this might sound ridiculous, but you don't have to keep another terminal tab open. For my case, this is related to _almost_ non-technical people who write markdown plus maybe some CSS and they already use pow.

I feel you about having no dependencies. Do you think there is a way to have _optional_ rack support? It's ok if you completely against that, I don't want to bother in any case.

**Comment by garybernhardt** [comment]
In that case, I think you only want the Rebuilder class, which is 40 lines long. I don't want to maintain an actual gem plus a Rack interface to expose that. Perhaps if this comes up a lot in the future.

**Comment by krasnoukhov** [comment]
Yeah, sounds good. Thanks!
